language: cpp
compiler:
- clang
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq autoconf automake libtool pkg-config flex bison libpq5
  libpq-dev
- clang -v
script:
- set -e
- ./autogen.sh
- ./configure
- make -j $(nproc)
- make check
notifications:
  email: false
  slack:
    secure: VYA87p8f6PgmOhL8b8DM4t6k8vPYjULpT7LBhvmNBNe8iiNDtTzLpRbUXg6t6Ij7Y3MU4uOJ5K617hCqs81VfRoOakbiYTWHeYSsMmIrUM4+d5MZM4pVP0/bCE49qt06bZINorh6IHChhfuvod3uyUqbgNrwRf/qDIIboFDIty8=
