language: cpp
compiler:
- clang
- gcc
cache: apt
before_install:
- wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
- sudo apt-get update -qq
- sudo apt-get install -qq python-software-properties
- sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'
- sudo add-apt-repository -y 'ppa:ubuntu-toolchain-r/test'
- sudo apt-get update -qq
- sudo apt-get install -qq autoconf automake libtool pkg-config flex bison clang-3.5 llvm-3.5 libstdc++6 libpq5 libpq-dev
- clang -v
script:
- set -e
- ./autogen.sh
- ./configure
- make -j $(nproc)
- make check
notifications:
  email: false
  slack:
    secure: VYA87p8f6PgmOhL8b8DM4t6k8vPYjULpT7LBhvmNBNe8iiNDtTzLpRbUXg6t6Ij7Y3MU4uOJ5K617hCqs81VfRoOakbiYTWHeYSsMmIrUM4+d5MZM4pVP0/bCE49qt06bZINorh6IHChhfuvod3uyUqbgNrwRf/qDIIboFDIty8=
