sudo: required
language: cpp
compiler:
  - clang
  - gcc
addons:
  - postgresql: "9.3"
cache:
  - apt
  - directories:
    - $HOME/.ccache
    - .libs
script: ./travis-build.sh
notifications:
  email: false
  slack:
    secure: VYA87p8f6PgmOhL8b8DM4t6k8vPYjULpT7LBhvmNBNe8iiNDtTzLpRbUXg6t6Ij7Y3MU4uOJ5K617hCqs81VfRoOakbiYTWHeYSsMmIrUM4+d5MZM4pVP0/bCE49qt06bZINorh6IHChhfuvod3uyUqbgNrwRf/qDIIboFDIty8=
branches:
  only:
    - auto
